In [2]:
import numpy as np

mmatrix= np.array([[1,2,3],[4,5,6]])
print(mmatrix)

[[1 2 3]
 [4 5 6]]


In [4]:
#Sigmoid
#sigmoid function
def sigmoid(X):
   return 1/(1+np.exp(-X))

#Example with mmatrix defined above
sigmoid(mmatrix)



array([[0.73105858, 0.88079708, 0.95257413],
       [0.98201379, 0.99330715, 0.99752738]])

In [5]:
#ReLu function
def relu(X):
   return np.maximum(0,X)
#Example with mmatrix defined above
relu(mmatrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#softmax function
def softmax(X):
    expo = np.exp(X)
    expo_sum = np.sum(np.exp(X))
    return expo/expo_sum
#Example with mmatrix defined above
print (softmax(mmatrix))

[[0.00426978 0.01160646 0.03154963]
 [0.08576079 0.23312201 0.63369132]]
